### ISSUE TITLE
sign transaction with bip0143 not support?

### ISSUE THREAD

**Issue by jerryxmm** [moneybutton/bsv#104]
I want to use this bsv library, but I found sign transaction with bip0143 does not support, can you add me as a directly contributor?

**Comment by mathiasrw** [comment]
Awesome if you would like to look into this. I suggest you fork the repo, do your changes in your version and make a pull request (PR) fixing this issue.

**Comment by bitcartel** [comment]
This issue can probably be closed.  The sig hashing scheme in BSV is inherited from Bitcoin Cash which itself was based on BIP143.  The differences e.g. FORKID, mean that it doesn't make sense to backport a non-BSV sig hashing scheme into the BSV library itself.

For reference:
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/abc/replay-protected-sighash.md
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki

**Comment by ryanxcharles** [comment]
This is obsolete for bsv 2.0.
