### ISSUE TITLE
404 errors in Documentation Index links, looking for mnemonics docs

### ISSUE THREAD

**Issue by bitcoinappdev** [moneybutton/bsv#105]
At this page: https://github.com/moneybutton/bsv/blob/master/docs/index.md

I'm getting 404 / Page not found errors when I click the majority of the links under "Documentation Index". 

I'm especially looking for the mnemonics docs if anyone can provide a working link, thank you!

**Comment by ryanxcharles** [comment]
Please see:

https://docs.moneybutton.com
