### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by mathiasrw** [moneybutton/bsv#110]
I suggest next release is named 1.0.0 and starting to use semantic versioning to indicate breaking changes, added features and fixes/patches in the version number. 

I know keeping 0.x.y might seem more "be carefull what you do with this update" but i much rather raise the version number to 56.x.y over the years than not really know the meaning between a 0.44.2 and 0.45.0

**Comment by ryanxcharles** [comment]
good suggestion. done.
