### ISSUE TITLE
how to connect the network.livenet? any demo code?

### ISSUE THREAD

**Issue by lijianl** [moneybutton/bsv#139]

**Comment by lijianl** [comment]
json rpc connect failed..

**Comment by afomi** [comment]
Are you able to reproduce this issue?

The error message seems communicative and accurate. An RPC called failed.

Check /docs and tests for sample code.

**Comment by lijianl** [comment]
are there any  bsv public node available? the /docs  and /test do not have an RPC client sample

**Comment by ryanxcharles** [comment]
This library does not connect to RPC.
