### ISSUE TITLE
How to get address and private key from a mnemonic?

### ISSUE THREAD

**Issue by soulmachine** [moneybutton/bsv#140]
Basically I need a function as the following:

```typescript
export function getBSVAddress(mnemonic: string): { address: string; privateKey: string } {
  return { address: 'xxx', privateKey: 'yyy' };
}
```

I've done similar  things with other coins such as BTC, BCH, EOS, ETH quite smoothly, but I'm having a hard time with this library, any suggestions?

**Comment by hojarasca** [comment]
Hi! You can find information here:

https://docs.moneybutton.com/docs/bsv-mnemonic.html
https://docs.moneybutton.com/docs/bsv-hd-private-key.html
https://docs.moneybutton.com/docs/bsv-hd-public-key.html

You need to include bsv and bsv/mnemonic. And then you can derive keys and create addreses:

``` js
const mnemonic = new bsv.Mnemonic()
const hdPrivKey = bsv.HDPrivKey.fromSeed(mnemonic.toSeed())
const someKey = hdPrivateKey.deriveChild("m/5/2/8") // Private key
const somePubkey = someKey.publicKey
const address = somePubKey.toAddress()
```

I did this from my memory, so there might be some mistake, but in those docs I sent there are details about this.

**Comment by hojarasca** [comment]
I closed the thread by mistake. Feel free to close if the question was answered.

**Comment by soulmachine** [comment]
Finally make it work:

```typescript
// import * as bip39 from 'bip39';
import * as bip39 from 'bip39';
import bsv from 'bsv';

// eslint-disable-next-line import/prefer-default-export
export function getBSVAddressFromMnemonic(
  mnemonic: string,
): { address: string; privateKey: string } {
  const seed = bip39.mnemonicToSeedSync(mnemonic);
  // const seed = Mnemonic.fromString(mnemonic).toSeed(); // TypeError: Cannot read property 'fromString' of undefined
  const hdPrivateKey = bsv.HDPrivateKey.fromSeed(seed, bsv.Networks.mainnet);

  const child = hdPrivateKey.deriveChild("m/44'/236'/0'/0/0");

  const address = child.publicKey.toAddress(bsv.Networks.mainnet);

  return { address: address.toString(), privateKey: child.privateKey.toWIF() };
}
```

**Comment by mathiasrw** [comment]
@soulmachine Why the `236` in `hdPrivateKey.deriveChild("m/44'/236'/0'/0/0");` ?

**Comment by soulmachine** [comment]
@mathiasrw  According to this [SLIP-0044 : Registered coin types for BIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md), BSV standard path is `m/44'/236'/0'/0/0`
