### ISSUE TITLE
Same Input can be passed multiple times

### ISSUE THREAD

**Issue by Siko91** [moneybutton/bsv#146]
In ```Transaction.prototype.from``` there is a check to see if the new UTXO is in fact one of the old ones. This Check however expects certain fields in the object, that might not be there:

This is the check:
```js
  var exists = _.some(this.inputs, function (input) {
    // TODO: Maybe prevTxId should be a string? Or defined as read only property?
    return input.prevTxId.toString('hex') === utxo.txId && input.outputIndex === utxo.outputIndex
  })
  if (exists) {
    return this
  }
```

This check expects the fields ```txId``` and ```outputIndex``` to be present.
The problem is that the later code doesn't only work with these fields. It can also work with ```txid``` and ```vout```.

If the passed inputs are like:

```js
tx.from({ txid: "same txid", vout: 0, amount:100000, scriptPubKey: "same script" });
tx.from({ txid: "same txid", vout: 0, amount:100000, scriptPubKey: "same script" });
tx.from({ txid: "same txid", vout: 0, amount:100000, scriptPubKey: "same script" });
tx.from({ txid: "same txid", vout: 0, amount:100000, scriptPubKey: "same script" });
```

...then the check will pass. and all of these will be added as separate inputs, even though they are the same.

The way to fix this bug is either to move the check Down (to a moment After it is transformed to an input), or to move the transformation Up ( move ```utxo = new UnspentOutput(utxo)``` to the moment before any checks are made. )

**Comment by ryanxcharles** [comment]
This is obsolete for bsv 2.0.
