### ISSUE TITLE
please add paymail query api

### ISSUE THREAD

**Issue by flufy3d** [moneybutton/bsv#172]
or add a legacy address where the bsv come from .add this data to webhook call back

**Comment by flufy3d** [comment]
I got signaturePubkey in webhook callback.
but How can I get the bitcoin address that I can send it back?

**Comment by flufy3d** [comment]
`
        paymailClient.getPublicKey(payment.senderPaymail).then(pubkey => {
          const pubkey_inst = bsv.PublicKey.fromString(pubkey)
          let address = bsv.Address.fromPublicKey(pubkey_inst).toString()
          let amount = payment.satoshis/2
          console.log(`send to ${address} ${amount} sats, paymail: ${payment.senderPaymail} pubkey: ${pubkey}`)
        })
`

I tried this ,but the address is wrong I can't recieve the money

**Comment by ryanxcharles** [comment]
paymail and webhooks have nothing to do with this library
