### ISSUE TITLE
version compatible

### ISSUE THREAD

**Issue by lijianl** [moneybutton/bsv#197]
why the new version not compatible with the old one, such as 1.5.4;

the new version is hard to use...very disgusting update

**Comment by mathiasrw** [comment]
@lijianl It would be great if you could point our where you were expecting it to be compatible and experienced it to not be. 

And to call an update "discusting" on free software is so unconsidered of the time put in by the individuals to make it all work. Please focus on the technical aspects.

**Comment by calvogenerico** [comment]
Hello @lijianl . When the upgrade from 1.x to 2.x was made there was discussion between the community. It wasn't something that happen from one day to the other. Also, we only release the stable 2.x when there was one big system using it.

We understand that migrate is a problem. But we hope to make bsv 2.x as good as possible, in a way that the migration really worth the effort.

The code style in 2.x is totally different than 1.x. But I invite you to read both source codes. You'll se that the new version is a lot easier to understand and maintain.

The big missing part is documentation. I started a few times to write things but I never got anything really complete. If you have specific questions feel free to ask in any of the bsv slacks or directly to me via telegram (@hojarasca).

Also, the library is well tested. You can always check the unit test to see how things are suppose to work.

**Comment by calvogenerico** [comment]
Closing this issue, I don't believe there is anything to do here.
