### ISSUE TITLE
ECIES implement

### ISSUE THREAD

**Issue by monkeylord** [moneybutton/bsv#20]
For now, there's no standard or BIP about ECIES, and there are different implements which are incompatible with each other.
So we need to choose one, but I think bitcore's implement is not as good as electrum's implement.
There are reasons:
1. bitcore's implement does not contain a 'magic word' for message to identify itself, while electrum's implement contain a magic word 'BIE1' which will not confuse decryption.
2. Electrum's implement introduced ephemeral keys, which allow encrypt message just with Public Key, and decrypt message just with Private Key. Revealing sender's public key is optional, not a must.
3. Electrum wallets (Electron Cash/ElectrumSV) are not compatible with bitcore-ecies.

Thus, I suggest we use electrum-ecies instead of bitcore-ecies.

**Comment by ryanxcharles** [comment]
Sounds good to me. Please issue a PR with full test coverage that fixes our implementation to be the same as Electrum.
