### ISSUE TITLE
'testnet' address generation bug?

### ISSUE THREAD

**Issue by antmaster2001** [moneybutton/bsv#220]
Hello, today is my first day using the bsv package.

I'm trying to generate a 'testnet' address following the code in the documentation.

```javascript
const bsv = require("bsv");
let privateKey = bsv.PrivKey.fromRandom('testnet')
let publicKey = bsv.PubKey.fromPrivKey(privateKey)
let address = bsv.Address.fromPubKey(publicKey, 'testnet')
let address2 = bsv.Address.fromPrivKey(privateKey, 'testnet')

console.log(address.toString());
console.log(address2.toString());
```

No matter how many times I try, they all start with a 1.

```
example: 1B9ymVLbAMkwY87rNugSxqfx7V1hGw71xX
```

Am I making a mistake or is there something wrong with the documentation?

**Comment by sirdeggen** [comment]
Yes, you're making a small mistake. The documentation may be out of date - below works with the new bsv2 library v2 on I think

```javascript

let privateKey = bsv.PrivKey.Testnet.fromRandom()
let publicKey = bsv.PubKey.fromPrivKey(privateKey)
let address = bsv.Address.Testnet.fromPubKey(publicKey)
let address2 = bsv.Address.Testnet.fromPrivKey(privateKey)

console.log(address.toString())
console.log(address2.toString())
```

**Comment by antmaster2001** [comment]
I just checked and that works perfect 😃 The code I added is straight from the [Docs](https://docs.moneybutton.com/docs/bsv/bsv-address.html)

**Comment by sirdeggen** [comment]
Such is documentation sadly.
