### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by nao360** [moneybutton/bsv#24]
![image](https://user-images.githubusercontent.com/6898065/52063422-89ca2c00-256a-11e9-8184-1d5526ba26bc.png)

'Against' is misspelled in the 'Bitcoin SV changes' section of README.md; second sentence, 8th word.

I tried submitting a pull request (because typos drive me nuts :sweat_smile: ), but alas, I'm not authorised.

**Comment by bitcartel** [comment]
This issue can be closed as documentation has moved to https://github.com/moneybutton/docs.
