### ISSUE TITLE
BSV SigHash confusing me

### ISSUE THREAD

**Issue by gitzhou** [moneybutton/bsv#4]
Hi there,

The sentence in README,

> Bitcoin sv uses a different sighash for transaction signatures.

What does this exactly mean...

I've read code [lib/crypto/signature.js](https://github.com/moneybutton/bsv/blob/master/lib/crypto/signature.js)
```
Signature.SIGHASH_ALL = 0x01;
Signature.SIGHASH_NONE = 0x02;
Signature.SIGHASH_SINGLE = 0x03;
Signature.SIGHASH_FORKID = 0x40;
Signature.SIGHASH_ANYONECANPAY = 0x80;
```

code [lib/transaction/sighash.js](https://github.com/moneybutton/bsv/blob/master/lib/transaction/sighash.js#L159)

```
function sighash(transaction, sighashType, inputNumber, subscript, satoshisBN, flags)
...
```

compare with [code](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/core_write.cpp#L62) in [bitcoin-sv/bitcoin-sv](https://github.com/bitcoin-sv/bitcoin-sv) repo

```
const std::map<uint8_t, std::string> mapSigHashTypes = {
    {SIGHASH_ALL, "ALL"},
    {SIGHASH_ALL | SIGHASH_ANYONECANPAY, "ALL|ANYONECANPAY"},
    {SIGHASH_ALL | SIGHASH_FORKID, "ALL|FORKID"},
    {SIGHASH_ALL | SIGHASH_FORKID | SIGHASH_ANYONECANPAY,
     "ALL|FORKID|ANYONECANPAY"},
    {SIGHASH_NONE, "NONE"},
    {SIGHASH_NONE | SIGHASH_ANYONECANPAY, "NONE|ANYONECANPAY"},
    {SIGHASH_NONE | SIGHASH_FORKID, "NONE|FORKID"},
    {SIGHASH_NONE | SIGHASH_FORKID | SIGHASH_ANYONECANPAY,
     "NONE|FORKID|ANYONECANPAY"},
    {SIGHASH_SINGLE, "SINGLE"},
    {SIGHASH_SINGLE | SIGHASH_ANYONECANPAY, "SINGLE|ANYONECANPAY"},
    {SIGHASH_SINGLE | SIGHASH_FORKID, "SINGLE|FORKID"},
    {SIGHASH_SINGLE | SIGHASH_FORKID | SIGHASH_ANYONECANPAY,
     "SINGLE|FORKID|ANYONECANPAY"},
};
```

and code [src/script/sighashtype.h](https://github.com/bitcoin-sv/bitcoin-sv/blob/d9b12a23dbf0d2afc5f488fa077d762b302ba873/src/script/sighashtype.h#L14)

```
/** Signature hash types/flags */
enum {
    SIGHASH_ALL = 1,
    SIGHASH_NONE = 2,
    SIGHASH_SINGLE = 3,
    SIGHASH_FORKID = 0x40,
    SIGHASH_ANYONECANPAY = 0x80,
};
```

I didn't quite understand, what's the difference that BSV SigHash has, compared with BitcoinCash(BCH)

Would you please kindly help and teach me about this?
For my understandings, SigHash logic that BCH and BSV used, are the same, currently
Is there a plan of removing the `SIGHASH_FORKID` or changing the value? 

Thanks very much for you helping and teaching 😄

**Comment by ryanxcharles** [comment]
there is no difference in the BSV sighash from BCH.

**Comment by gitzhou** [comment]
> there is no difference in the BSV sighash from BCH.

Thanks @ryanxcharles
