### ISSUE TITLE
about version guard

### ISSUE THREAD

**Issue by monkeylord** [moneybutton/bsv#74]
It seems that the version guard error is quite annoying when requiring multiple modules that depend on bsv.
> More than one instance of bsv found. Please make sure to require bsv and check that submodules do not also include their own bsv dependency.

1. Should we change the error to a warning?
2. Should there be a global bsv instance?

Maybe we should change version guard in index.js, by using a global bsv instance in somewhere like global._bsvInstance ?

**Comment by bitcartel** [comment]
This issue is closed by PR https://github.com/moneybutton/bsv/pull/86 which has merged.
