### ISSUE TITLE
Throws error when parsing specific tx output script

### ISSUE THREAD

**Issue by kevinejohn** [moneybutton/bsv#90]
When parsing this transaction's (https://whatsonchain.com/tx/ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767) output scripts bsv throws this error:

```
Error
    at new NodeError (/project/node_modules/bsv/lib/errors/index.js:20:41)
    at Function.Script.fromBuffer (/project/node_modules/bsv/lib/script/script.js:101:15)
{
  message: "Invalid script buffer: can't parse valid script from given buffer 4e",
```

Looks like this was fixed for bitcoinjs-lib:
https://github.com/bitcoinjs/bitcoinjs-lib/pull/375

**Comment by ryanxcharles** [comment]
Closing due to imminent release of bsv 2.0. Please let me know if you still have this issue.

I believe the bitcore ASM format is fundamentally broken and may not be able to resolve this issue ever - you may need to use one of the other formats. There are 3 string formats in the new library.
