### ISSUE TITLE
TypeError: Buffer.alloc is not a function

### ISSUE THREAD

**Issue by Gamaroff** [moneybutton/bsv#92]
Hi have an Angular 7 app and have imported the bsv library.

The app displays the following error:

```
TypeError: Buffer.alloc is not a function
    at Object../node_modules/bsv/lib/util/buffer.js (.../node_modules/bsv/lib/util/buffer.js:176:1)
```

Tried a whole bunch of things and failed miserably.
Any pointers greatly appreciated.

**Comment by Gamaroff** [comment]
I have a feeling it has something to do with @types/node

**Comment by Gamaroff** [comment]
SOLVED.

In polyfills.ts do the following:

```
import { Buffer } from 'buffer';
import * as process from 'process';

(window as any).global = window;
(window as any).Buffer = Buffer;
(window as any).process = process;

```

I had made the mistake of not including the 'process' module and I had incorrectly imported the 'buffer' module as follows:

```
import * as buffer from 'buffer';
```

Hope this helps someone in the future.

**Comment by ryejoon** [comment]
@Gamaroff It did. 👍 Thank you!
